improv: Better NVIDIA package origin detection
pop-os/shop pull request #223
Opened 2020-09-24 18:56 UTC by mmstick

2020-09-24 19:11 UTC, jackpot51 approved these changes

2020-09-24 19:11 UTC, jackpot51 commented
Nice

2020-09-25 17:18 UTC, jackpot51 approved these changes

2020-09-25 22:56 UTC, jacobgkau requested changes
I'm seeing `nvidia-driver-450` (version 450.66) offered on the serw12 after adding this branch (`fdafd93`). It goes away when I revert to master (`f37e26a`). (The current release in the PPA,`889726a`, doesn't have the fix from a few days ago yet, so it's still offering 450.66 as well.)

2022-04-18 22:52 UTC, closed without merging